#!/usr/bin/env node

/* tslint:disable */

// hook into ts-node so we can run typescript on the fly
require('ts-node').register({ project: `${__dirname}/tsconfig.json` })
// kick off gluegun
require(`${__dirname}/index`)
